spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to microservices cards related QA APIs "
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "fil@microservices.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267