server:
  port: 8091
spring:
  application:
    name: "cards"
  profiles:
        active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#uncomment in order to run else we take error
#   config:
#     import:
#       - "application_qa.yml"
#       - "application_prod.yml"
#   profiles:
#     active:
#       - "qa"

# build:
#   version: "3.0"

# cards:
#   message: "Welcome to microservices cards related local APIs "
#   contactDetails:
#     name: "Dragos Lech - Developer"
#     email: "fil@microservices.com"
#   onCallSupport:
#     - (412) 419-3491
#     - (915) 382-1932