spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to microservices cards related prod APIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "fil@microservices.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721