services:
  accounts:
    image: "fkon123/accounts:bankApp"
    container_name: "accounts-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankApp
  loans:
    image: "fkon123/loans:bankApp"
    #build:
      #context: .
      #dockerfile: Dockerfile
    container_name: "loans-ms"
    ports:
      - "8092:8092"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankApp
  cards:
    image: "fkon123/cards:bankApp"
    container_name: "cards-ms"
    ports:
      - "8091:8091"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankApp
networks:
  bankApp:
    driver: "bridge"