spring:
    config:
        activate:
            on-profile: "prod"

build:
    version: "3.0"

accounts:
    message: "Hello World PROD API"
    contactDetails:
        name: "fil123"
        email: "fil13kon@gmail.com"
    onCallSupport:
        - (555) 555-5555
        - (666) 666-6666

