spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to microservices loans related QA APIs "
  contactDetails:
    name: "Cyrano Marita - QA Lead"
    email: "fil@microservices.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467